blank_issues_enabled: false
contact_links:
  - name: Community Discord
    url: https://discord.gg/kadena
    about: Please ask and answer questions here.
  - name: GitHub Discussions
    url: https://github.com/Kadena-Pact-Community-Foundation/foundation/discussions
    about: For longer-form discussions and proposals.
