title: Pact Community Organization
description: Making it easy and safe for businesses to start building with Pact
theme: jekyll-theme-minimal

url: "https://www.pact-community.org"

# Build settings
markdown: kramdown
